import json
import re
import uuid

INPUT_FILE = "/home/a/code/al-mizan-project/almizan-etl/data/semantichadith/SemanticHadith-V2/SemanticHadithKGV2.ttl"
OUTPUT_JSONL = "/home/a/code/al-mizan-project/almizan-etl/hadith_nodes.jsonl"
OUTPUT_SURQL = "/home/a/code/al-mizan-project/almizan-etl/output/semantic_hadith.surql"

def extract_lang_values(text):
    """Extract all language-tagged values from a TTL property line."""
    # Pattern: "text content"^^xsd:string or "text@lang"^^xsd:string
    pattern = r'"([^"]+)(?:@(\w+))?"\^\^xsd:string'
    matches = re.findall(pattern, text)
    result = {}
    for content, lang in matches:
        lang = lang if lang else 'en'
        # Skip placeholder values
        if content != '0':
            result[lang] = content.strip()
    return result

def process_file():
    print(f"Reading {INPUT_FILE}...")
    hadith_count = 0
    
    with open(INPUT_FILE, 'r', encoding='utf-8') as f_in, \
         open(OUTPUT_JSONL, 'w', encoding='utf-8') as f_jsonl, \
         open(OUTPUT_SURQL, 'w', encoding='utf-8') as f_surql:
        
        # Write SurrealQL header
        f_surql.write("-- SemanticHadith V2 Import\n")
        f_surql.write("-- Generated by ingest_semantichadith.py\n\n")
        
        buffer = []
        
        for line in f_in:
            line = line.strip()
            
            if not line or line.startswith('#'):
                if not buffer: 
                    continue
            
            buffer.append(line)
            
            if line.endswith('.'):
                full_block = " ".join(buffer)
                
                # Check if this block defines a Hadith instance
                if ":Hadith" in full_block and ("rdf:type" in full_block or " a " in full_block) and "owl:Class" not in full_block:
                    
                    hadith_obj = {
                        "id": f"semantic_hadith:{hadith_count + 1}",
                        "type": "hadith",
                        "source": "semantichadith_v2",
                        "collection": "ibn_majah"  # Primary source in V2
                    }
                    
                    # Extract fullHadithText with language variants
                    text_match = re.search(r':fullHadithText\s+(.+?)(?:;|$)', full_block, re.DOTALL)
                    if text_match:
                        lang_values = extract_lang_values(text_match.group(1))
                        if 'ar' in lang_values:
                            hadith_obj["body_ar"] = lang_values['ar']
                        if 'ur' in lang_values:
                            hadith_obj["body_ur"] = lang_values['ur']
                    
                    # Extract reference number
                    ref_match = re.search(r':hadithReferenceNo\s+"(\d+)"', full_block)
                    if ref_match:
                        hadith_obj["ref_no"] = int(ref_match.group(1))
                    
                    # Extract narrator
                    narrator_match = re.search(r':hasRootNarrator\s+:(\w+)', full_block)
                    if narrator_match:
                        hadith_obj["narrator_id"] = narrator_match.group(1)
                    
                    # Only write if we have Arabic body
                    if "body_ar" in hadith_obj:
                        # Write JSONL
                        f_jsonl.write(json.dumps(hadith_obj, ensure_ascii=False) + "\n")
                        
                        # Write SurrealQL - escape quotes properly
                        ref_no = hadith_obj.get("ref_no", hadith_count + 1)
                        # Use json.dumps to safely serialize string content (handles quotes, backslashes, etc.)
                        body_ar_json = json.dumps(hadith_obj["body_ar"], ensure_ascii=False)
                        narrator = hadith_obj.get("narrator_id", "unknown")
                        narrator_json = json.dumps(narrator, ensure_ascii=False)
                        
                        f_surql.write(f"CREATE semantic_hadith:{ref_no} SET ")
                        f_surql.write(f"ref_no = {ref_no}, ")
                        f_surql.write(f"body_ar = {body_ar_json}, ")
                        f_surql.write(f"narrator_id = {narrator_json}, ")
                        f_surql.write(f"collection = 'ibn_majah';\n")
                        
                        hadith_count += 1
                        if hadith_count % 1000 == 0:
                            print(f"Processed {hadith_count} hadiths...")
                
                buffer = []

    print(f"Done. Generated {hadith_count} hadiths.")
    print(f"  JSONL: {OUTPUT_JSONL}")
    print(f"  SurQL: {OUTPUT_SURQL}")

if __name__ == "__main__":
    process_file()
